--customer card view
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."CUSTOMER_CARD_V" ("C_ID", "CARD_NAME", "CARD_TYPE") DEFAULT COLLATION "USING_NLS_COMP"  AS SELECT c_id,card_name,card_type FROM Customer_Card_Details;

--customer view
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."CUSTOMER_V" ("C_ID", "C_FIRSTNAME", "C_LASTNAME", "C_USERNAME") DEFAULT COLLATION "USING_NLS_COMP"  AS SELECT c_id, c_firstname, c_lastname, c_username FROM Customer;

--owner view
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."OWNER_V" ("O_ID", "O_FIRSTNAME", "O_LASTNAME", "O_USERNAME") DEFAULT COLLATION "USING_NLS_COMP"  AS SELECT o_id, o_firstname, o_lastname, o_username FROM Owner;